### ISSUE TITLE
Add an onComplete callback function

### ISSUE THREAD

**Issue by jhadenfeldt** [bameyrick/scroll-to-position#1]
It would be helpful to have a callback function that gets called once a scroll animation is completed.

Something like this:

```
ScrollTo([500, 0], {
    onComplete: function() {
        console.log('scrolling complete');
    }
})
```

**Comment by bameyrick** [comment]
This is possible using `.then` as calling `ScrollTo` returns a promise. I've [updated the docs](https://github.com/bameyrick/scroll-to-position#callback) to covert this.

**Comment by jhadenfeldt** [comment]
Oh, nice - that's even better!
